export enum ScheduleSituations {
  OPENED = 'OPENED',
  SCHEDULED = 'SCHEDULED',
  WAITING = 'WAITING',
  RECEIVING = 'RECEIVING',
  RECEIVED = 'RECEIVED',
  FINISHED = 'FINISHED',
  CANCELED = 'CANCELED',
  NON_RECEIVED = 'NON_RECEIVED',
  RESCHEDULED = 'RESCHEDULED'
}
