export const OPEN_EDIT_OPENED_SCHEDULE = 'OPEN_EDIT_OPENED_SCHEDULE'
export const OPEN_EDIT_OPENED_SCHEDULE_PAYLOAD =
  'OPEN_EDIT_OPENED_SCHEDULE_PAYLOAD'

export const OPEN_EDIT_CLOSED_SCHEDULE = 'OPEN_EDIT_CLOSED_SCHEDULE'
export const OPEN_EDIT_CLOSED_SCHEDULE_PAYLOAD =
  'OPEN_EDIT_CLOSED_SCHEDULE_PAYLOAD'
