import { WinThorSalesByProviderRepository } from 'repositories/implementations/WinThorSalesByProviderRepository'

import { FindSalesByProviderPerProductSalesValueController } from './FindSalesByProviderPerProductSalesValueController'
import { FindSalesByProviderPerProductSalesValueUseCase } from './FindSalesByProviderPerProductSalesValueUseCase'

const winThorSalesByProviderRepository = new WinThorSalesByProviderRepository()

const findSalesByProviderPerProductSalesValueUseCase = new FindSalesByProviderPerProductSalesValueUseCase(
  winThorSalesByProviderRepository
)

const findSalesByProviderPerProductSalesValueController = new FindSalesByProviderPerProductSalesValueController(
  findSalesByProviderPerProductSalesValueUseCase
)

export {
  findSalesByProviderPerProductSalesValueController,
  findSalesByProviderPerProductSalesValueUseCase
}
