export const OPEN_PROVIDER_FINDER_WINDOW = 'OPEN_PROVIDER_FINDER_WINDOW'
export const OPEN_PROVIDER_FINDER_WINDOW_RESULT =
  'OPEN_PROVIDER_FINDER_WINDOW_RESULT'
export const OPEN_PROVIDER_FINDER_WINDOW_PAYLOAD =
  'OPEN_PROVIDER_FINDER_WINDOW_PAYLOAD'
