export const OPEN_BUYER_FINDER_WINDOW = 'OPEN_BUYER_FINDER_WINDOW'
export const OPEN_BUYER_FINDER_WINDOW_RESULT = 'OPEN_BUYER_FINDER_WINDOW_RESULT'
export const OPEN_BUYER_FINDER_WINDOW_PAYLOAD =
  'OPEN_BUYER_FINDER_WINDOW_PAYLOAD'
